package message

const (
	InvalidDate       = "This value is not a valid date."
	InvalidDateTime   = "This value is not a valid datetime."
	InvalidJSON       = "This value should be valid JSON."
	InvalidTime       = "This value is not a valid time."
	IsBlank           = "This value should not be blank."
	IsEqual           = "This value should not be equal to {{ comparedValue }}."
	IsNil             = "This value should not be nil."
	NoSuchChoice      = "The value you selected is not a valid choice."
	NotBlank          = "This value should be blank."
	NotDivisible      = "This value should be a multiple of {{ comparedValue }}."
	NotDivisibleCount = "The number of elements in this collection should be a multiple of {{ divisibleBy }}."
	NotEqual          = "This value should be equal to {{ comparedValue }}."
	NotExactCount     = "This collection should contain exactly {{ limit }} element(s)."
	NotExactLength    = "This value should have exactly {{ limit }} character(s)."
	NotFalse          = "This value should be false."
	NotInRange        = "This value should be between {{ min }} and {{ max }}."
	NotInteger        = "This value is not an integer."
	NotNegative       = "This value should be negative."
	NotNegativeOrZero = "This value should be either negative or zero."
	NotNil            = "This value should be nil."
	NotNumeric        = "This value is not a numeric."
	NotPositive       = "This value should be positive."
	NotPositiveOrZero = "This value should be either positive or zero."
	NotTrue           = "This value should be true."
	NotUnique         = "This collection should contain only unique elements."
	NotValid          = "This value is not valid."
	ProhibitedIP      = "This IP address is prohibited to use."
	ProhibitedURL     = "This URL is prohibited to use."
	TooEarly          = "This value should be later than {{ comparedValue }}."
	TooEarlyOrEqual   = "This value should be later than or equal to {{ comparedValue }}."
	TooFewElements    = "This collection should contain {{ limit }} element(s) or more."
	TooHigh           = "This value should be less than {{ comparedValue }}."
	TooHighOrEqual    = "This value should be less than or equal to {{ comparedValue }}."
	TooLate           = "This value should be earlier than {{ comparedValue }}."
	TooLateOrEqual    = "This value should be earlier than or equal to {{ comparedValue }}."
	TooLong           = "This value is too long. It should have {{ limit }} character(s) or less."
	TooLow            = "This value should be greater than {{ comparedValue }}."
	TooLowOrEqual     = "This value should be greater than or equal to {{ comparedValue }}."
	TooManyElements   = "This collection should contain {{ limit }} element(s) or less."
	TooShort          = "This value is too short. It should have {{ limit }} character(s) or more."
)
